{
 "title": "Nginx_exporter",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nginx status",
   "type": "stat",
   "description": "Is nginx up or down ?",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_exporter_build_info", "legendFormat": "__auto" }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Nginx_connections_accepted",
   "type": "gauge",
   "description": "Total number of connections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_accepted", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nginx connections handled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "nginx_connections_handled", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nginx_connections_active",
   "type": "timeseries",
   "description": "Total active connections",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "__auto" },
    { "expr": "nginx_connections_reading", "legendFormat": "__auto" },
    { "expr": "nginx_connections_waiting", "legendFormat": "__auto" },
    { "expr": "nginx_connections_writing", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nginx total http requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "__auto" }
   ]
  }
 ]
}