export { default as Welcome } from './Welcome'
export { default as SignIn } from './SignIn'
export { default as SignUp } from './SignUp'
export { default as Auth2 } from './Auth2'
export { default as Dashboard } from './Dashboard'